name: Fullstack DApp CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Python Backend Checks
  backend-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint Python
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics
      - name: Run Python tests
        run: |
          pytest || true

  # Solidity Smart Contract Checks
  contracts-solidity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Hardhat and dependencies
        run: npm ci
      - name: Lint Solidity
        run: npx solhint 'backend/*.sol'
      - name: Run Hardhat tests
        run: npx hardhat test --network hardhat --config hardhat.config.js || true

  # Solidity Static Analysis (using Slither)
  contracts-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install solc from PPA and Slither
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc python3-pip
          pip install slither-analyzer
      - name: Run Slither Analysis
        run: |
          slither backend --json slither-report.json
        continue-on-error: true
      - name: Upload Slither report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json

  # Frontend (React) Checks
  frontend-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Lint React code
        run: npm run lint || true
      - name: Run React tests
        run: npm test -- --watchAll=false || true
      - name: Build React app
        run: npm run build
        
